### ISSUE TITLE
Support Documentation Online Redirection

### ISSUE THREAD

**Issue by slcott** [ppwwyyxx/dash-docset-tensorflow#1]
https://kapeli.com/docsets#onlineRedirection

> Support Documentation Online Redirection

> Starting with version 3.0, Dash users can open the online version of pages inside docsets. To do that, Dash needs to know where to find the online pages for your docset.

> You have 2 options to support online redirection:

> Set the DashDocSetFallbackURL key in your docset's Info.plist. The value should be the base URL of the docs. Example: https://docs.python.org/3/library/
Alternatively, add a HTML comment inside each and every HTML file of your docset. The comment needs to be added next to the <html> tag of the pages and should look like this:

> ```
><html>
>```

**Comment by ppwwyyxx** [comment]
Looks like it should work by setting fallback url to https://www.tensorflow.org/.

However I use zeal instead of dash, so I cannot test this. 

Could you try the solution and post the modified `Info.plist` file if it works? Then I could update with this support. A PR would be even better.
Thanks

**Comment by slcott** [comment]
>Could you try the solution and post the modified Info.plist file if it works? 

Sure.

I made one small change to `dashing.json`

```
"externalURL": "https://www.tensorflow.org/",
```

I submitted the PR.
