### ISSUE TITLE
Tensorflow 2.0 docset

### ISSUE THREAD

**Issue by yantijin** [ppwwyyxx/dash-docset-tensorflow#8]
Tensorflow 2.0 comes in September. Ant ideas about changing the docsets version to tf2.0? Thx!

**Comment by blvz** [comment]
FWIW, I compiled TF 2.1 docs myself.

[TensorFlow.docset.tar.gz](https://github.com/ppwwyyxx/dash-docset-tensorflow/files/4385716/TensorFlow.docset.tar.gz)

**Comment by xmuwenxiang** [comment]
> FWIW, I compiled TF 2.1 docs myself.
> 
> [TensorFlow.docset.tar.gz](https://github.com/ppwwyyxx/dash-docset-tensorflow/files/4385716/TensorFlow.docset.tar.gz)

thanks

**Comment by ppwwyyxx** [comment]
Docset for TF2.10 was released in this repo.
